### ISSUE TITLE
Sugestão de licença

### ISSUE THREAD

**Issue by Hinigatsu** [raylansoares/rose-server#1]
Seria legal ter uma LICENSE nos três projetos que deixassem explícito as condições do uso do software.

# Sugestões:
[WTFPL](https://choosealicense.com/licenses/wtfpl/)

ou

[GPL 3](https://choosealicense.com/licenses/gpl-3.0/), e (https://choosealicense.com/licenses/agpl-3.0/) aonde necessário.
___
Mais licenças em: https://choosealicense.com/

**Comment by raylansoares** [comment]
Adicionado
